### ISSUE TITLE
documents(WordPress) Missing steps

### ISSUE THREAD

**Issue by mrEckendonk** [Highfivery/nextjs-starter#18]
Currently, parts are missing about the WordPress configuration.

https://github.com/Highfivery/nextjs-starter/wiki/WordPress-Setup

Create Pages​
In the WordPress Dashboard, navigate to Pages -> Add New

Create three blank pages named:

Homepage
Blog
404

For the 404 I could not find the settings. Settings -> Headless Config -> Custom Page Options

As I don't have a crystal ball, I don't know if you're simplifying this also.

**Comment by bmarshall511** [comment]
Hey @mrEckendonk, we're still in heavy dev & haven't released any versions.... yet. Actually hoping to get the first beta release out today. Once the release is out, the docs will be updated to support the latest release. For now, many things are probably... off.

With that being said, I actually updated that doc 3 hours ago with the latest instructions. Still needs more info, but if you'd like to contribute... happy for the help. Otherwise, try to hold off until the first beta release.

**Comment by mrEckendonk** [comment]
@bmarshall511 Let me know how I can contribute. I'm very interested in this project since the moment that I bumped into the old abandoned one.

**Comment by bmarshall511** [comment]
@mrEckendonk Thanks for your interest! You can contribute however you'd like where you see a need for improvements, depending on your expertise and what you want to work on. Currently & for the beta release, we're focusing on WordPress integration so doing a lot of work building the integration of the Gutenberg Ant Design WP plugin (https://github.com/Highfivery/wordpress-gutenberg-ant-design). 

Once the beta version is released, you can check the issue queue for ideas of where you can contribute.
